name: Test CI

on: 
  push:
  pull_request:

env:
  qemu-version: 8.2.0
  rust-toolchain: nightly-2024-05-02

jobs:
  app-test-for-unikernel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64, riscv64, aarch64]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.rust-toolchain }}
        components: rust-src
    - uses: Swatinem/rust-cache@v2
    - run: cargo install cargo-binutils
    - uses: ./.github/workflows/actions/setup-qemu
      with:
        qemu-version: ${{ env.qemu-version }}
    - uses: ./.github/workflows/actions/setup-musl
      with:
        arch: ${{ matrix.arch }}
    - name: Run app tests
      run: |
        make disk_img
        make test ARCH=${{ matrix.arch }}

  app-test-for-monolithic:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64, riscv64, aarch64]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.rust-toolchain }}
        components: rust-src
    - uses: Swatinem/rust-cache@v2
    - run: cargo install cargo-binutils
    - uses: ./.github/workflows/actions/setup-qemu
      with:
        qemu-version: ${{ env.qemu-version }}
    - uses: ./.github/workflows/actions/setup-musl
      with:
        arch: ${{ matrix.arch }}
    - name: Run app tests
      run: |
        make disk_img
        make test_monolithic ARCH=${{ matrix.arch }}
  app-test-for-ext4fs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64, riscv64, aarch64]   
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.rust-toolchain }}
        components: rust-src
    - uses: Swatinem/rust-cache@v2
    - run: cargo install cargo-binutils
    - uses: ./.github/workflows/actions/setup-qemu
      with:
        qemu-version: ${{ env.qemu-version }}
    - uses: ./.github/workflows/actions/setup-musl
      with:
        arch: ${{ matrix.arch }}
    - name: Run app tests
      run: |
        sh ./build_img.sh -a ${{ matrix.arch }} -fs ext4
        export MONOLITHIC_TESTCASE=other
        make ARCH=${{ matrix.arch }} A=apps/monolithic_userboot APP_FEATURES=batch FEATURES="lwext4_rust" LOG=off ACCEL=n run
        make clean
        make ARCH=${{ matrix.arch }} A=apps/monolithic_userboot APP_FEATURES=batch FEATURES="ext4_rs" LOG=off ACCEL=n run